<a href="https://colab.research.google.com/github/abhi147p/Abhishek_INFO5731_Spring2023/blob/main/In_class_exercise_03_02282023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (2/28/2023, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

For an online shopping, there are various platforms, such as amazon, flipkart, walmart etc.. for purchasing different products. To know which item
is better of all the items on single product, we have to analyze the data based on different features available in the platform, such as title, 
brand, price, discount and ratings. We need to scrape all the data present in platform for the analysis. Here I am using the flipkart platform for
analysing the various products data. We can categorize the best products among all others by applying various machine learning techniques. 
Also collecting the customer reviews will be more helpful in advance, based on similar interests.

For this task, the important features are:
1) Title
2) url
3) brand
4) price
5) discount
6) Free delivery



'''

Question 2 (10 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [28]:
# You code here (Please add comments in the code):

import requests
from bs4 import BeautifulSoup
import re
import time
import pandas as pd

def get_soup(url):
    """
        params1: url (contains the url of google scholar page)
        return: soup (fetching the url page data and then further converted to html parser)
    """
  # headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'}
    headers = {'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36')}
               # 'X-User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 FKUA/website/42/website/Desktop')}
    try:
        # requesting for data using requests with url and headers for authentication
        data = requests.get(url, headers=headers)
        # print(f"Extracted the data with response as {data.status_code}")
        if data.status_code != 200:
            raise Exception(f"Failed to fetch data: {data.status_code} and text as {data.text}")
    except Exception as ex:
        print(f"Exception occurred as {ex}")
        return None
    soup = BeautifulSoup(data.text, "html.parser")
    return soup

def fetch_data_web(pages):

  final_data = []
  for i in range(1, pages+1):
    url = f"https://www.flipkart.com/search?q=Watches&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={i}"
    soup = get_soup(url)
    # print(soup.prettify())
    products_data = soup.findAll("div", attrs={"class": "_1AtVbE col-12-12"})
    for prod_data in products_data:
      sub_prod_data = prod_data.findAll("div", attrs={"class": "_1xHGtK _373qXS"})
      for data in sub_prod_data:
        prod_url = "https://www.flipkart.com" + data.find("a", attrs={"class": "_2UzuFa"}).get("href")
        brand = data.find("div", attrs={"class": "_2WkVRV"}).text.strip()
        title = data.find("a", attrs={"class": "IRpwTa"}).get("title")
        new_price = data.find("div", attrs={"class": "_30jeq3"}).text.strip()
        old_price = data.find("div", attrs={"class": "_3I9_wc"}).text.strip()
        discount = data.find("div", attrs={"class": "_3Ay6Sb"}).text.strip()
        free_delivery = data.find("div", attrs={"class": "_2Tpdn3"})
        if free_delivery:
          free_delivery = free_delivery.text.strip()
        else:
          free_delivery = "No free Delivery"
        soup_data = get_soup(prod_url)
        # print(prod_url)
        # print(soup_data)
        # break
        # rating = "0"
        # if soup_data:
        if soup_data:
          rating = soup_data.find("div", attrs={"class": "_3LWZlK _3uSWvT"}).text
        else:
          rating = "No rating found"
        final_data.append([title, prod_url, brand, new_price, old_price, discount, rating, free_delivery])
      time.sleep(1)
    print(f"Processed {i} pages")
  
  df = pd.DataFrame(final_data, columns=["Title", "url", "brand", "new_price", "old_price", "discount", "rating", "Delivery"])
  return df

df = fetch_data_web(int(input("Enter no of pages: ")))
df.head()

Enter no of pages: 2
Processed 1 pages
Processed 2 pages

,Title,url,brand,new_price,old_price,discount,rating,Delivery
0,Men's and Women's Watch Box Holder Organizer C...,https://www.flipkart.com/ledo-men-s-women-s-wa...,LEDO,₹949,"₹3,999",76% off,4.6,Free delivery
1,G-Shock ( GST-B100-1ADR ) Analog Watch - For Men,https://www.flipkart.com/casio-gst-b100-1adr-g...,CASIO,"₹19,449","₹24,995",22% off,4.4,Free delivery
2,Magnetic Chain magnet strap with bracelet hand...,https://www.flipkart.com/nester-movable-round-...,NESTER,₹199,"₹1,299",84% off,4.1,Free delivery
3,Combo of 2 Analog Watch Analog Watch - For Men,https://www.flipkart.com/hala-miller-combo-2-a...,hala,₹199,"₹1,499",86% off,4,Free delivery
4,Digital Watch - For Men,https://www.flipkart.com/hala-digital-watch-me...,hala,₹199,₹999,80% off,3.9,Free delivery

In [29]:
df.shape

(80, 8)

In [32]:
df[df.rating=="No rating found"]

Empty DataFrame
Columns: [Title, url, brand, new_price, old_price, discount, rating, Delivery]
Index: []

In [63]:
# converting str to numeric

df['new_price'] = df['new_price'].str.replace(',', '').str[1:]
df['old_price'] = df['old_price'].str.replace(',', '').str[1:]
df['discount'] = v['discount'].str.replace("%","")
for x in range(len(df)):
  df.loc[x, "discount"] = df.loc[x, "discount"].split()[0].strip()

df.head()

,Title,url,brand,new_price,old_price,discount,rating,Delivery
0,Men's and Women's Watch Box Holder Organizer C...,https://www.flipkart.com/ledo-men-s-women-s-wa...,LEDO,949,3999,76,4.6,Free delivery
1,G-Shock ( GST-B100-1ADR ) Analog Watch - For Men,https://www.flipkart.com/casio-gst-b100-1adr-g...,CASIO,19449,24995,22,4.4,Free delivery
2,Magnetic Chain magnet strap with bracelet hand...,https://www.flipkart.com/nester-movable-round-...,NESTER,199,1299,84,4.1,Free delivery
3,Combo of 2 Analog Watch Analog Watch - For Men,https://www.flipkart.com/hala-miller-combo-2-a...,hala,199,1499,86,4,Free delivery
4,Digital Watch - For Men,https://www.flipkart.com/hala-digital-watch-me...,hala,199,999,80,3.9,Free delivery

In [64]:
df['new_price'] = df['new_price'].astype(int)
df['new_price'].head()

0      949
1    19449
2      199
3      199
4      199
Name: new_price, dtype: int64

In [68]:
df['old_price'] = df['old_price'].astype(int)
df['discount'] = df['discount'].astype(int)
df['rating'] = df['rating'].astype(float)

df.head()

,Title,url,brand,new_price,old_price,discount,rating,Delivery
0,Men's and Women's Watch Box Holder Organizer C...,https://www.flipkart.com/ledo-men-s-women-s-wa...,LEDO,949,3999,76,4.6,Free delivery
1,G-Shock ( GST-B100-1ADR ) Analog Watch - For Men,https://www.flipkart.com/casio-gst-b100-1adr-g...,CASIO,19449,24995,22,4.4,Free delivery
2,Magnetic Chain magnet strap with bracelet hand...,https://www.flipkart.com/nester-movable-round-...,NESTER,199,1299,84,4.1,Free delivery
3,Combo of 2 Analog Watch Analog Watch - For Men,https://www.flipkart.com/hala-miller-combo-2-a...,hala,199,1499,86,4.0,Free delivery
4,Digital Watch - For Men,https://www.flipkart.com/hala-digital-watch-me...,hala,199,999,80,3.9,Free delivery

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      80 non-null     object
 1   url        80 non-null     object
 2   brand      80 non-null     object
 3   new_price  80 non-null     int64
 4   old_price  80 non-null     int64
 5   discount   80 non-null     int64
 6   rating     80 non-null     float64
 7   Delivery   80 non-null     object
dtypes: float64(1), int64(3), object(4)
memory usage: 5.1+ KB

In [78]:
# rounding up ratings
for x in range(len(df)):
  df.loc[x, "rating"] = int(round(df.loc[x, "rating"],0))
df['rating'] = df['rating'].astype(int)
df.head()

,Title,url,brand,new_price,old_price,discount,rating,Delivery
0,Men's and Women's Watch Box Holder Organizer C...,https://www.flipkart.com/ledo-men-s-women-s-wa...,LEDO,949,3999,76,5,Free delivery
1,G-Shock ( GST-B100-1ADR ) Analog Watch - For Men,https://www.flipkart.com/casio-gst-b100-1adr-g...,CASIO,19449,24995,22,4,Free delivery
2,Magnetic Chain magnet strap with bracelet hand...,https://www.flipkart.com/nester-movable-round-...,NESTER,199,1299,84,4,Free delivery
3,Combo of 2 Analog Watch Analog Watch - For Men,https://www.flipkart.com/hala-miller-combo-2-a...,hala,199,1499,86,4,Free delivery
4,Digital Watch - For Men,https://www.flipkart.com/hala-digital-watch-me...,hala,199,999,80,4,Free delivery

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [82]:
# You code here (Please add comments in the code):

# The features used in above paper is  filter, wrapper, embedded and hybrid, Using 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# splitting data into X(independent) and y(target) var
X = df[['new_price', 'old_price', 'discount']].to_numpy()
y = df['rating']
selector = SelectKBest(chi2, k=3)
selector.fit(X, y)
print('χ² statistic', selector.scores_)
print('Selected indices', selector.get_support(True))

χ² statistic [1.25208681e+00 2.48132050e+03 5.13271609e-01]
Selected indices [0 1 2]

In [88]:
rank_df = pd.DataFrame(selector.scores_, columns=["Scores"])
rank_df["features"] = ["new_price", "old_price", "discount"]
rank_df.sort_values(by = ['Scores'], inplace=True, ascending=False)
rank_df.head()

        Scores   features
1  2481.320503  old_price
0     1.252087  new_price
2     0.513272   discount

Question 4 (10 points): Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [ ]:
# You code here (Please add comments in the code):